ci(macos): Align macos script with current linux
Also use venv instead of global install
brew/python doesn't like installing python packages globally:
```
error: externally-managed-environment
× This environment is externally managed
```