ci: Add permissions necessary for release-please
Without this it fails with this error:
```
Error: release-please failed: Resource not accessible by integration
```
The `issues: write` permissions are needed to create labels on PRs,
because of this issue: https://github.com/orgs/community/discussions/156181
Followup to https://github.com/scop/bash-completion/pull/1432